"""initial schema

Revision ID: 653d5970d9ca
Revises:
Create Date: 2026-09-10 15:51:31.312655

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "653d5970d9ca"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discord_channels",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("district_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("webhook_id", sa.BigInteger(), nullable=True),
        sa.Column("webhook_token", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel_id"),
        sa.UniqueConstraint("district_id", "kind", name="uq_discord_channels_district_kind"),
    )
    op.create_index(
        op.f("ix_discord_channels_district_id"), "discord_channels", ["district_id"], unique=False
    )
    op.create_table(
        "district_state",
        sa.Column("district_id", sa.Integer(), nullable=False),
        sa.Column("tick", sa.Integer(), nullable=False),
        sa.Column("quota_progress", sa.Float(), nullable=False),
        sa.Column("quota_target", sa.Float(), nullable=False),
        sa.Column("morale", sa.Float(), nullable=False),
        sa.Column("unrest", sa.Float(), nullable=False),
        sa.Column("peacekeeper_pressure", sa.Float(), nullable=False),
        sa.Column("crisis_level", sa.Integer(), nullable=False),
        sa.Column("crisis_kind", sa.String(length=32), nullable=True),
        sa.Column("capitol_favor", sa.Float(), nullable=False),
        sa.Column("victor_bonus_until", sa.Integer(), nullable=True),
        sa.Column("treasury", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("district_id"),
    )
    op.create_table(
        "inventories",
        sa.Column("owner_kind", sa.String(length=16), nullable=False),
        sa.Column("owner_id", sa.String(length=64), nullable=False),
        sa.Column("good_id", sa.String(length=64), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("owner_kind", "owner_id", "good_id"),
    )
    op.create_table(
        "market_orders",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("district_id", sa.Integer(), nullable=False),
        sa.Column("good_id", sa.String(length=64), nullable=False),
        sa.Column("owner_kind", sa.String(length=16), nullable=False),
        sa.Column("owner_id", sa.String(length=64), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("tick", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_market_orders_district_id"), "market_orders", ["district_id"], unique=False
    )
    op.create_table(
        "market_prices",
        sa.Column("district_id", sa.Integer(), nullable=False),
        sa.Column("good_id", sa.String(length=64), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("supply", sa.Float(), nullable=False),
        sa.Column("demand", sa.Float(), nullable=False),
        sa.Column("tick", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("district_id", "good_id"),
    )
    op.create_table(
        "memories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("owner_kind", sa.String(length=16), nullable=False),
        sa.Column("owner_id", sa.String(length=64), nullable=False),
        sa.Column("tick", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("importance", sa.Integer(), nullable=False),
        sa.Column("subject_kind", sa.String(length=16), nullable=True),
        sa.Column("subject_id", sa.String(length=64), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("expires_tick", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_memories_owner_id"), "memories", ["owner_id"], unique=False)
    op.create_table(
        "npcs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("district_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=True),
        sa.Column("traits", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("speech_style", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("faction_leanings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("location_id", sa.String(length=64), nullable=True),
        sa.Column("x", sa.Float(), nullable=True),
        sa.Column("y", sa.Float(), nullable=True),
        sa.Column("home_location_id", sa.String(length=64), nullable=True),
        sa.Column("money", sa.Float(), nullable=False),
        sa.Column("float_target", sa.Float(), nullable=False),
        sa.Column("shop_goods", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("hunger", sa.Float(), nullable=False),
        sa.Column("health", sa.Float(), nullable=False),
        sa.Column("fear", sa.Float(), nullable=False),
        sa.Column("loyalty", sa.Float(), nullable=False),
        sa.Column("morale", sa.Float(), nullable=False),
        sa.Column("avatar_url", sa.String(length=512), nullable=True),
        sa.Column("importance", sa.Integer(), nullable=False),
        sa.Column("alive", sa.Boolean(), nullable=False),
        sa.Column("provider_override", sa.String(length=16), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_npcs_district_id"), "npcs", ["district_id"], unique=False)
    op.create_table(
        "relationships",
        sa.Column("subject_kind", sa.String(length=16), nullable=False),
        sa.Column("subject_id", sa.String(length=64), nullable=False),
        sa.Column("object_kind", sa.String(length=16), nullable=False),
        sa.Column("object_id", sa.String(length=64), nullable=False),
        sa.Column("affinity", sa.Integer(), nullable=False),
        sa.Column("trust", sa.Float(), nullable=False),
        sa.Column("last_interaction_tick", sa.Integer(), nullable=True),
        sa.Column("stance", sa.String(length=16), nullable=False),
        sa.Column("stance_updated_tick", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("subject_kind", "subject_id", "object_kind", "object_id"),
    )
    op.create_table(
        "staff_actions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("staff_discord_id", sa.BigInteger(), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_staff_actions_staff_discord_id"),
        "staff_actions",
        ["staff_discord_id"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("discord_id", sa.BigInteger(), nullable=False),
        sa.Column("tos_accepted_at", sa.DateTime(), nullable=True),
        sa.Column("banned_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_discord_id"), "users", ["discord_id"], unique=True)
    op.create_table(
        "world_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tick", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("district_id", sa.Integer(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("announced", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_world_events_announced"), "world_events", ["announced"], unique=False)
    op.create_index(
        op.f("ix_world_events_district_id"), "world_events", ["district_id"], unique=False
    )
    op.create_index(op.f("ix_world_events_kind"), "world_events", ["kind"], unique=False)
    op.create_index(op.f("ix_world_events_tick"), "world_events", ["tick"], unique=False)
    op.create_table(
        "characters",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("district_id", sa.Integer(), nullable=False),
        sa.Column("current_district_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("appearance", sa.String(length=400), nullable=False),
        sa.Column("backstory", sa.String(length=1500), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=True),
        sa.Column("job_started_tick", sa.Integer(), nullable=True),
        sa.Column("consecutive_missed", sa.Integer(), nullable=False),
        sa.Column("reputation", sa.Float(), nullable=False),
        sa.Column("money", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.String(length=64), nullable=True),
        sa.Column("x", sa.Float(), nullable=True),
        sa.Column("y", sa.Float(), nullable=True),
        sa.Column("avatar_url", sa.String(length=512), nullable=True),
        sa.Column("proxy_tag", sa.String(length=12), nullable=True),
        sa.Column("loyalty", sa.Float(), nullable=False),
        sa.Column("fear", sa.Float(), nullable=False),
        sa.Column("health", sa.Float(), nullable=False),
        sa.Column("hunger", sa.Float(), nullable=False),
        sa.Column("hospitalized", sa.Boolean(), nullable=False),
        sa.Column("tesserae_count", sa.Integer(), nullable=False),
        sa.Column("jailed_until_tick", sa.Integer(), nullable=True),
        sa.Column("in_games", sa.Boolean(), nullable=False),
        sa.Column("is_victor", sa.Boolean(), nullable=False),
        sa.Column("in_transit_until_tick", sa.Integer(), nullable=True),
        sa.Column("transit_destination_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "proxy_tag", name="uq_character_user_proxy_tag"),
    )
    op.create_index(op.f("ix_characters_district_id"), "characters", ["district_id"], unique=False)
    op.create_index(op.f("ix_characters_status"), "characters", ["status"], unique=False)
    op.create_index(op.f("ix_characters_user_id"), "characters", ["user_id"], unique=False)
    op.create_table(
        "npc_schedule",
        sa.Column("npc_id", sa.String(length=64), nullable=False),
        sa.Column("phase", sa.String(length=16), nullable=False),
        sa.Column("location_id", sa.String(length=64), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["npc_id"],
            ["npcs.id"],
        ),
        sa.PrimaryKeyConstraint("npc_id", "phase", "location_id"),
    )
    op.create_table(
        "jobs_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("started_tick", sa.Integer(), nullable=False),
        sa.Column("ended_tick", sa.Integer(), nullable=True),
        sa.Column("reason", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_jobs_history_character_id"), "jobs_history", ["character_id"], unique=False
    )
    op.create_table(
        "scenes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("district_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.String(length=64), nullable=False),
        sa.Column("thread_id", sa.BigInteger(), nullable=False),
        sa.Column("forum_channel_id", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("created_by_character_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("pins_location", sa.Boolean(), nullable=False),
        sa.Column("last_message_at", sa.DateTime(), nullable=True),
        sa.Column("participants", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_character_id"],
            ["characters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("thread_id"),
    )
    op.create_index(op.f("ix_scenes_district_id"), "scenes", ["district_id"], unique=False)
    op.create_index(op.f("ix_scenes_last_message_at"), "scenes", ["last_message_at"], unique=False)
    op.create_index(op.f("ix_scenes_location_id"), "scenes", ["location_id"], unique=False)
    op.create_index(op.f("ix_scenes_status"), "scenes", ["status"], unique=False)
    op.create_table(
        "shifts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("tick_opened", sa.Integer(), nullable=False),
        sa.Column("tick_due", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.Integer(), nullable=True),
        sa.Column("result", sa.String(length=16), nullable=True),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_shifts_character_id"), "shifts", ["character_id"], unique=False)
    op.create_table(
        "dialogue_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tick", sa.Integer(), nullable=False),
        sa.Column("npc_id", sa.String(length=64), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=True),
        sa.Column("scene_id", sa.Integer(), nullable=True),
        sa.Column("provider", sa.String(length=24), nullable=False),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("output", sa.Text(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("flagged", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scene_id"],
            ["scenes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dialogue_log_npc_id"), "dialogue_log", ["npc_id"], unique=False)
    op.create_table(
        "scene_messages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scene_id", sa.Integer(), nullable=False),
        sa.Column("thread_id", sa.BigInteger(), nullable=False),
        sa.Column("district_id", sa.Integer(), nullable=False),
        sa.Column("discord_message_id", sa.BigInteger(), nullable=False),
        sa.Column("author_kind", sa.String(length=16), nullable=False),
        sa.Column("author_id", sa.String(length=64), nullable=True),
        sa.Column("author_name", sa.String(length=64), nullable=False),
        sa.Column("avatar_url", sa.String(length=512), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("ts", sa.DateTime(), nullable=False),
        sa.Column("edited_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["scene_id"],
            ["scenes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("discord_message_id"),
    )
    op.create_index(
        op.f("ix_scene_messages_district_id"), "scene_messages", ["district_id"], unique=False
    )
    op.create_index(
        op.f("ix_scene_messages_scene_id"), "scene_messages", ["scene_id"], unique=False
    )
    op.create_index(
        op.f("ix_scene_messages_thread_id"), "scene_messages", ["thread_id"], unique=False
    )
    op.create_index(op.f("ix_scene_messages_ts"), "scene_messages", ["ts"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scene_messages_ts"), table_name="scene_messages")
    op.drop_index(op.f("ix_scene_messages_thread_id"), table_name="scene_messages")
    op.drop_index(op.f("ix_scene_messages_scene_id"), table_name="scene_messages")
    op.drop_index(op.f("ix_scene_messages_district_id"), table_name="scene_messages")
    op.drop_table("scene_messages")
    op.drop_index(op.f("ix_dialogue_log_npc_id"), table_name="dialogue_log")
    op.drop_table("dialogue_log")
    op.drop_index(op.f("ix_shifts_character_id"), table_name="shifts")
    op.drop_table("shifts")
    op.drop_index(op.f("ix_scenes_status"), table_name="scenes")
    op.drop_index(op.f("ix_scenes_location_id"), table_name="scenes")
    op.drop_index(op.f("ix_scenes_last_message_at"), table_name="scenes")
    op.drop_index(op.f("ix_scenes_district_id"), table_name="scenes")
    op.drop_table("scenes")
    op.drop_index(op.f("ix_jobs_history_character_id"), table_name="jobs_history")
    op.drop_table("jobs_history")
    op.drop_table("npc_schedule")
    op.drop_index(op.f("ix_characters_user_id"), table_name="characters")
    op.drop_index(op.f("ix_characters_status"), table_name="characters")
    op.drop_index(op.f("ix_characters_district_id"), table_name="characters")
    op.drop_table("characters")
    op.drop_index(op.f("ix_world_events_tick"), table_name="world_events")
    op.drop_index(op.f("ix_world_events_kind"), table_name="world_events")
    op.drop_index(op.f("ix_world_events_district_id"), table_name="world_events")
    op.drop_index(op.f("ix_world_events_announced"), table_name="world_events")
    op.drop_table("world_events")
    op.drop_index(op.f("ix_users_discord_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_staff_actions_staff_discord_id"), table_name="staff_actions")
    op.drop_table("staff_actions")
    op.drop_table("relationships")
    op.drop_index(op.f("ix_npcs_district_id"), table_name="npcs")
    op.drop_table("npcs")
    op.drop_index(op.f("ix_memories_owner_id"), table_name="memories")
    op.drop_table("memories")
    op.drop_table("market_prices")
    op.drop_index(op.f("ix_market_orders_district_id"), table_name="market_orders")
    op.drop_table("market_orders")
    op.drop_table("inventories")
    op.drop_table("district_state")
    op.drop_index(op.f("ix_discord_channels_district_id"), table_name="discord_channels")
    op.drop_table("discord_channels")
    # ### end Alembic commands ###
