"""add per-user character limit override

Revision ID: 687efdd9a58a
Revises: 0fb3bf76f733
Create Date: 2026-09-11 01:14:03.190675

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "687efdd9a58a"
down_revision: str | None = "0fb3bf76f733"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("max_characters_override", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "max_characters_override")
    # ### end Alembic commands ###
