"""add world_clock table

Revision ID: 6fc777554ae5
Revises: 687efdd9a58a
Create Date: 2026-09-11 04:23:31.324713

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6fc777554ae5"
down_revision: str | None = "687efdd9a58a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "world_clock",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tick", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("world_clock")
    # ### end Alembic commands ###
