"""unique index on character name (case-insensitive, excludes rejected)

Revision ID: 7116c3213f6e
Revises: c52648bdeebc
Create Date: 2026-09-10 22:39:50.685551

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7116c3213f6e"
down_revision: str | None = "c52648bdeebc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_characters_name_ci",
        "characters",
        [sa.literal_column("lower(name)")],
        unique=True,
        postgresql_where=sa.text("status <> 'rejected'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_characters_name_ci",
        table_name="characters",
        postgresql_where=sa.text("status <> 'rejected'"),
    )
    # ### end Alembic commands ###
